import React from 'react';
import { Trans, withTranslation } from 'react-i18next';
import { COMMENT_LINE_DEFAULT_TOKEN } from '../../../../helpers/constants';
const Examples = (props) => (React.createElement("div", { className: "list leading-loose" },
    React.createElement(Trans, null, "examples_title"),
    ":",
    React.createElement("ol", { className: "leading-loose" },
        React.createElement("li", null,
            React.createElement("code", null, "94.140.14.140"),
            ", ",
            React.createElement("code", null, "2a10:50c0::1:ff"),
            ": ",
            props.t('example_upstream_regular')),
        React.createElement("li", null,
            React.createElement("code", null, "94.140.14.140:53"),
            ", ",
            React.createElement("code", null, "[2a10:50c0::1:ff]:53"),
            ":",
            ' ',
            props.t('example_upstream_regular_port')),
        React.createElement("li", null,
            React.createElement("code", null, "udp://unfiltered.adguard-dns.com"),
            ": ",
            React.createElement(Trans, null, "example_upstream_udp")),
        React.createElement("li", null,
            React.createElement("code", null, "tcp://94.140.14.140"),
            ", ",
            React.createElement("code", null, "tcp://[2a10:50c0::1:ff]"),
            ":",
            ' ',
            React.createElement(Trans, null, "example_upstream_tcp")),
        React.createElement("li", null,
            React.createElement("code", null, "tcp://94.140.14.140:53"),
            ", ",
            React.createElement("code", null, "tcp://[2a10:50c0::1:ff]:53"),
            ":",
            ' ',
            React.createElement(Trans, null, "example_upstream_tcp_port")),
        React.createElement("li", null,
            React.createElement("code", null, "tcp://unfiltered.adguard-dns.com"),
            ": ",
            React.createElement(Trans, null, "example_upstream_tcp_hostname")),
        React.createElement("li", null,
            React.createElement("code", null, "tls://unfiltered.adguard-dns.com"),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://en.wikipedia.org/wiki/DNS_over_TLS", target: "_blank", rel: "noopener noreferrer", key: "0" }, "DNS-over-TLS"),
                ] }, "example_upstream_dot")),
        React.createElement("li", null,
            React.createElement("code", null, "https://unfiltered.adguard-dns.com/dns-query"),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://en.wikipedia.org/wiki/DNS_over_HTTPS", target: "_blank", rel: "noopener noreferrer", key: "0" }, "DNS-over-HTTPS"),
                ] }, "example_upstream_doh")),
        React.createElement("li", null,
            React.createElement("code", null, "h3://unfiltered.adguard-dns.com/dns-query"),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://en.wikipedia.org/wiki/HTTP/3", target: "_blank", rel: "noopener noreferrer", key: "0" }, "HTTP/3"),
                ] }, "example_upstream_doh3")),
        React.createElement("li", null,
            React.createElement("code", null, "quic://unfiltered.adguard-dns.com"),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://datatracker.ietf.org/doc/html/rfc9250", target: "_blank", rel: "noopener noreferrer", key: "0" }, "DNS-over-QUIC"),
                ] }, "example_upstream_doq")),
        React.createElement("li", null,
            React.createElement("code", null, "sdns://..."),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://dnscrypt.info/stamps/", target: "_blank", rel: "noopener noreferrer", key: "0" }, "DNS Stamps"),
                    React.createElement("a", { href: "https://dnscrypt.info/", target: "_blank", rel: "noopener noreferrer", key: "1" }, "DNSCrypt"),
                    React.createElement("a", { href: "https://en.wikipedia.org/wiki/DNS_over_HTTPS", target: "_blank", rel: "noopener noreferrer", key: "2" }, "DNS-over-HTTPS"),
                ] }, "example_upstream_sdns")),
        React.createElement("li", null,
            React.createElement("code", null, "[/example.local/]94.140.14.140"),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://github.com/nicelic/AdGuardHome-fork/wiki/Configuration#upstreams-for-domains", target: "_blank", rel: "noopener noreferrer", key: "0" }, "Link"),
                ] }, "example_upstream_reserved")),
        React.createElement("li", null,
            React.createElement("code", null, "[/example.local/]94.140.14.140 2a10:50c0::1:ff"),
            ":",
            ' ',
            React.createElement(Trans, { components: [
                    React.createElement("a", { href: "https://github.com/nicelic/AdGuardHome-fork/wiki/Configuration#upstreams-for-domains", target: "_blank", rel: "noopener noreferrer", key: "0" }, "Link"),
                ] }, "example_multiple_upstreams_reserved")),
        React.createElement("li", null,
            React.createElement("code", null,
                COMMENT_LINE_DEFAULT_TOKEN,
                " comment"),
            ": ",
            React.createElement(Trans, null, "example_upstream_comment")))));
export default withTranslation()(Examples);
