import React, { Fragment } from 'react';
import { withTranslation, Trans } from 'react-i18next';
const Examples = () => (React.createElement(Fragment, null,
    React.createElement("div", { className: "list leading-loose" },
        React.createElement(Trans, null, "examples_title"),
        ":",
        React.createElement("ol", { className: "leading-loose" },
            React.createElement("li", null,
                React.createElement("code", null, "||example.org^"),
                ":",
                React.createElement(Trans, null, "example_meaning_filter_block")),
            React.createElement("li", null,
                React.createElement("code", null, " @@||example.org^"),
                ":",
                React.createElement(Trans, null, "example_meaning_filter_whitelist")),
            React.createElement("li", null,
                React.createElement("code", null, "127.0.0.1 example.org"),
                ":",
                React.createElement(Trans, null, "example_meaning_host_block")),
            React.createElement("li", null,
                React.createElement("code", null,
                    React.createElement(Trans, null, "example_comment")),
                ":",
                React.createElement(Trans, null, "example_comment_meaning")),
            React.createElement("li", null,
                React.createElement("code", null,
                    React.createElement(Trans, null, "example_comment_hash")),
                ":",
                React.createElement(Trans, null, "example_comment_meaning")),
            React.createElement("li", null,
                React.createElement("code", null, "/REGEX/"),
                ":",
                React.createElement(Trans, null, "example_regex_meaning")))),
    React.createElement("p", { className: "mt-1" },
        React.createElement(Trans, { components: [
                React.createElement("a", { href: "https://link.adtidy.org/forward.html?action=dns_kb_filtering_syntax&from=ui&app=home", target: "_blank", rel: "noopener noreferrer", key: "0" }, "link"),
            ] }, "filtering_rules_learn_more"))));
export default withTranslation()(Examples);
